### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by warlord0** [R-Vision/wmi-client#2]
Not sure this is really in issue with this code as it runs if I `sudo`the command. Just clutching at straws trying to figure out what's going wrong.

```text
$ node resources/assets/js/wmi/query.js 
internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at wmic._exec (/var/www/servicemanager/node_modules/wmi-client/lib/wmic.js:145:16)
    at /var/www/servicemanager/node_modules/wmi-client/lib/wmic.js:127:22
    at /var/www/servicemanager/node_modules/getos/index.js:65:18
    at /var/www/servicemanager/node_modules/getos/logic/debian.js:18:5
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
```

I'm not sure where the `EACCESS` is coming from. I can run `/usr/bin/wmic` as the user and it's in the path so I can just call `wmic` directly.

Any suggestion gratefully received.

**Comment by NAlexandrov** [comment]
Hello! Check permissions:
```bash
ls -la /var/www/servicemanager/node_modules/wmi-client/bin
```
This directory has two version of static wmic utility for different operation systems. Try to set the permissions:
```
chmod -R +x /var/www/servicemanager/node_modules/wmi-client/bin
```

Or try to change wmic path:

```javascript
var wmi = new WmiClient({
    username: 'LOGIN',
    password: 'PASSWORD',
    host: 'IP-ADDRESS',
    wmic: '/usr/bin/wmic'
});
```
