### ISSUE TITLE
Can not work on ubuntu 14.04 with nodejs v8.3.0

### ISSUE THREAD

**Issue by caixiangshang** [R-Vision/wmi-client#4]
ENV:
```
os sys: ubuntu 14.04
node version: v8.3.0
```
Script: WMI_Client.js 
```
'use strict';

const WmiClient = require('wmi-client');

const wmi = new WmiClient({
    // windows login name
    username: 'qa',
    password: 'password',
   // windows IP
    host: '192.168.0.123'
});

wmi.query('SELECT * FROM Win32_Process', function (err, result) {
    console.log(err || result);
});

```
Error msg:
```
node WMI_Client.js 
internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at wmic._exec (/home/developer/e2e-test/sc-e2e-test/node_modules/wmi-client/lib/wmic.js:159:16)
    at /home/developer/e2e-test/sc-e2e-test/node_modules/wmi-client/lib/wmic.js:141:22
    at /home/developer/e2e-test/sc-e2e-test/node_modules/getos/index.js:100:16
    at /home/developer/e2e-test/sc-e2e-test/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/home/developer/e2e-test/sc-e2e-test/node_modules/async/dist/async.js:936:13)
    at /home/developer/e2e-test/sc-e2e-test/node_modules/async/dist/async.js:840:16
    at /home/developer/e2e-test/sc-e2e-test/node_modules/getos/index.js:95:18
```

**Comment by caixiangshang** [comment]
More info：
when I try below command to check wmi：
```
./node_modules/wmi-client/bin/wmic_ubuntu_x64
```
It returns error：
```
bash: ./wmic_ubuntu_x64: Permission denied
```
So I try to run the script `WMI_Client.js` with `sudo`,but there is no result and the terminal keep holding.

**Comment by caixiangshang** [comment]
@NAlexandrov Do you have any solutions?

**Comment by NAlexandrov** [comment]
Try to change permission:
```
chmod +x /home/developer/e2e-test/sc-e2e-test/node_modules/wmi-client/bin/wmic_ubuntu_x64
```
